---
- ec2:
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_ami_id }}"
    wait: yes
    count: 1
    group: "test-server"
    vpc_subnet_id: "{{ aws_subnet_id }}"
    assign_public_ip: yes
    region: "{{ aws_region_name }}"
    instance_tags: {"Name":"test-servers"}
    key_name: "{{ key_name }}"
  register: ec2_instance_details

- name: check Instance
  ec2_remote_facts:
    region: "{{ aws_region_name }}"
    filters:
      instance-state-name: running
      "tag:Name": "test-servers"
  register: instance_out

- name: Get the Public_ip
  ec2_remote_facts:
    region: "{{ aws_region_name }}"
    filters:
      ip-address: "{{ instance_out.instances[0].public_ip_address }}"
  register: instance_ip

- name: Debug ip address
  debug:
    var: instance_ip

- name: add IP hosts group
  add_host:
    name: "{{ item }}"
    groupname: test-instance-ip
  with_items: "{{ instance_ip.instances[0].public_ip_address }}"

- name: Wait for target instance to be up
  wait_for:
    host: "{{ instance_ip.instances[0].public_ip_address }}"
    port: 22
    state: started
    timeout: 600
    delay: 60


