---
- name: remove pam ccreds on Redhat systems
  yum: name='{{os_packages_pam_ccreds}}' state=absent

- name: remove pam_cracklib, because it does not play nice with passwdqc
  yum: name='{{os_packages_pam_cracklib}}' state='absent'
  when: os_auth_pam_passwdqc_enable

#- name: install the package for strong password checking
#  yum: name='{{os_packages_pam_passwdqc}}' state='installed'
#  when: os_auth_pam_passwdqc_enable

- name: remove passwdqc
  yum: name='{{os_packages_pam_passwdqc}}' state='absent'
  when: os_auth_pam_passwdqc_enable

#- name: configure passwdqc and tally via central system-auth confic
#  template: src='rhel_system_auth.j2' dest='/etc/pam.d/system-auth-ac' mode=0640 owner=root group=root

#- name: configure passwdqc and tally via central password-auth confic
#  template: src='rhel_password_auth.j2' dest='/etc/pam.d/password-auth-ac' mode=0640 owner=root group=root

- name: NSA 2.3.3.5 Upgrade Password Hashing Algorithm to SHA-512
  template: src='rhel_libuser.conf.j2' dest='/etc/libuser.conf' mode=0640 owner=root group=root
